### ISSUE TITLE
extra columns in CSV export

### ISSUE THREAD

**Issue by halmueller** [aaronr/geosync#10]
I've tried

<pre>
./geosync.py --flytrex test/00000004.FPV
</pre>

per the examples in README.md and I see this output:

<pre>
id,time,latitude,longitude,elevation
0,2014-10-02 01:01:04,47.787739,-122.1410896,40.185
1,2014-10-02 01:01:04,47.7877395,-122.1410903,39.565
2,2014-10-02 01:01:05,47.7877394,-122.1410912,39.618
</pre>

But the beginning of test/00000004.csv looks like this:

<pre>
latitude,longitude,altitude(feet),ascent(feet),speed(mph),distance(feet),max_altitude(feet),max_ascent(feet),max_speed(mph),max_distance(feet),time(millisecond),datetime(utc),datetime(local),satellites,pressure(Pa),temperature(F)
47.787740,-122.141090,130,0,0.05,0,130,0,0.05,0,0,2014-10-02 17:01:05.0000,2014-10-02 10:01:05.0000,04,101956,61.88
47.787739,-122.141091,130,0,0.03,0,130,0,0.05,0,250,2014-10-02 17:01:05.0250,2014-10-02 10:01:05.0250,04,101956,61.88
47.787739,-122.141092,130,1,0.03,0,130,1,0.05,0,500,2014-10-02 17:01:05.0500,2014-10-02 10:01:05.0500,04,101950,61.88
</pre>

What do I need to do to get the extra columns, as shown in the test folder's .CSV files?

**Comment by aaronr** [comment]
Hey there Hal.  The CSV is the original CSV produced by flytrex off their website and contains fields that we do not produce in our output.  This is not to say we can not add those fields, we just kept the default output of our tool simple (i.e. the stuff I needed for geotagging my photos for structure from motion stuff).  The CSV is archived there to allow us to validate the output of our tool is close to what is produced by flytrex.  Hope that makes sense.  If you want some pointers on adding other fields into the output let me know.
Also, would be interested in hearing what you are using the flytrex stuff for... always fun to learn from others adventures with this stuff!

**Comment by halmueller** [comment]
I'm tinkering with implementing a track viewer (and maybe a footprint viewer) for Mac/iPhone, using Apple's 3D framework SceneKit. I might just go with GPX files, but these CSV versions are simpler. I can derive course or heading, and pitch, from the position and elevation deltas.
